apisix:
  node_listen: 9080
  enable_admin: false
  ssl:
    enable: true
    listen:
      - port: 9443
        enable_http2: true
    #ssl_trusted_certificate: /somedirectory/certs/ca.crt
  control:
    ip: 0.0.0.0
    port: 9090
nginx_config:
  error_log: /dev/stderr
  stream:
    access_log: /dev/stdout
  http:
    access_log: /dev/stdout
  http_configuration_snippet: |
    proxy_buffering off;
deployment:
  role: data_plane
  role_data_plane:
    config_provider: yaml
discovery:
  kubernetes:
    service:
      schema: https
      host: "kubernetes.default"
      port: "443"
    client:
      token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
    default_weight: 50
  dns:
    servers:
      - "kube-dns.kube-system.svc.cluster.local"